services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\LoginAuthenticator:
        arguments:
            $userProvider: '@security.user.provider.concrete.app_user_provider'
            $passwordHasher: '@security.user_password_hasher'  # <-- service correct
            $router: '@router'

    App\Repository\:
        resource: '../src/Repository'
        tags: ['doctrine.repository_service']

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\MailService: 